import React, { useState, useMemo } from 'react';
import { X, Target, TrendingUp, Book, Award, Clock, CheckCircle, Circle, Brain, Zap, BarChart3, AlertCircle, Sparkles, Play, Download, Search } from 'lucide-react';
import { CAREER_DATABASE } from '../data/careerDatabase';

const SkillsGapAnalyzer = ({ onClose, darkMode }) => {
    const [step, setStep] = useState(1); // 1: Career selection, 2: Current skills, 3: Analysis & Roadmap
    const [selectedCareer, setSelectedCareer] = useState(null);
    const [currentSkills, setCurrentSkills] = useState([]);
    const [skillLevels, setSkillLevels] = useState({});
    const [analysis, setAnalysis] = useState(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [selectedDomain, setSelectedDomain] = useState('all');

    // Handler functions for buttons
    const handleStartLearning = (skillName) => {
        alert(`🎓 Starting learning resources for: ${skillName}\n\nRecommended platforms:\n• Coursera\n• Udemy\n• Khan Academy\n• YouTube\n• FreeCodeCamp`);
    };

    const handleExportPDF = () => {
        const content = `
CAREER READINESS REPORT
========================

Career: ${selectedCareer.name}
Readiness Score: ${analysis.readinessScore}%

SKILLS ACQUIRED (${analysis.matchingSkills.length}):
${analysis.matchingSkills.map((s, i) => `${i + 1}. ${s}`).join('\n')}

LEARNING ROADMAP (${analysis.learningPath.length} skills):
${analysis.learningPath.map((skill, i) => `
${i + 1}. ${skill.name}
   Level: ${skill.level}
   Category: ${skill.category}
   Priority: ${skill.importance}
   Time: ${skill.timeToLearn}
`).join('\n')}

Generated by COGNITRIAL Skills Gap Analyzer
    `.trim();

        // Create blob and download
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${selectedCareer.name.replace(/\s+/g, '_')}_Learning_Roadmap.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        alert('✅ Learning roadmap exported successfully!');
    };

    const handleEmailRoadmap = () => {
        const subject = encodeURIComponent(`My ${selectedCareer.name} Learning Roadmap`);
        const body = encodeURIComponent(`
Hi,

I've created a personalized learning roadmap for becoming a ${selectedCareer.name}.

Career Readiness Score: ${analysis.readinessScore}%
Skills to Learn: ${analysis.learningPath.length}
Estimated Time: ${analysis.totalMonths} months

Top Priority Skills:
${analysis.learningPath.slice(0, 5).map((skill, i) => `${i + 1}. ${skill.name} (${skill.timeToLearn})`).join('\n')}

Created with COGNITRIAL Skills Gap Analyzer.

Best regards
    `);

        window.location.href = `mailto:?subject=${subject}&body=${body}`;
    };

    const handleSaveForLater = () => {
        const roadmapData = {
            career: selectedCareer.name,
            readinessScore: analysis.readinessScore,
            matchingSkills: analysis.matchingSkills,
            learningPath: analysis.learningPath,
            totalMonths: analysis.totalMonths,
            savedAt: new Date().toISOString()
        };

        // Save to localStorage
        const savedRoadmaps = JSON.parse(localStorage.getItem('savedRoadmaps') || '[]');
        savedRoadmaps.push(roadmapData);
        localStorage.setItem('savedRoadmaps', JSON.stringify(savedRoadmaps));

        alert('✅ Roadmap saved successfully!\n\nYou can access it anytime from your saved roadmaps.');
    };

    // Get category for a skill
    const getCategoryForSkill = (skill, domain) => {
        const skillLower = skill.toLowerCase();

        if (skillLower.includes('programming') || skillLower.includes('coding') || skillLower.includes('software')) return 'Programming';
        if (skillLower.includes('design') || skillLower.includes('ui') || skillLower.includes('ux')) return 'Design';
        if (skillLower.includes('communication') || skillLower.includes('presentation')) return 'Soft Skills';
        if (skillLower.includes('analysis') || skillLower.includes('analytical')) return 'Analysis';
        if (skillLower.includes('management') || skillLower.includes('leadership')) return 'Management';
        if (skillLower.includes('medical') || skillLower.includes('clinical')) return 'Medical';
        if (skillLower.includes('research')) return 'Research';
        if (skillLower.includes('technical')) return 'Technical';

        return domain === 'technology' ? 'Technical' : domain === 'medical' ? 'Medical' : 'Core Skills';
    };

    // Get time estimate based on level
    const getTimeEstimate = (level) => {
        if (level === "Advanced") return `${3 + Math.floor(Math.random() * 3)} months`;
        if (level === "Intermediate") return `${2 + Math.floor(Math.random() * 2)} months`;
        return `${1 + Math.floor(Math.random() * 2)} months`;
    };

    // Get domain-specific additional skills
    const getDomainSpecificSkills = (domainKey, careerName) => {
        const commonSkills = {
            technology: [
                { name: "Problem Solving", level: "Advanced", category: "Core", importance: "Critical", timeToLearn: "4 months" },
                { name: "Programming Fundamentals", level: "Advanced", category: "Programming", importance: "Critical", timeToLearn: "5 months" },
                { name: "Data Structures", level: "Intermediate", category: "Programming", importance: "Important", timeToLearn: "3 months" }
            ],
            science: [
                { name: "Research Methodology", level: "Advanced", category: "Research", importance: "Critical", timeToLearn: "4 months" },
                { name: "Critical Thinking", level: "Advanced", category: "Analysis", importance: "Critical", timeToLearn: "3 months" },
                { name: "Laboratory Skills", level: "Intermediate", category: "Technical", importance: "Important", timeToLearn: "3 months" }
            ],
            engineering: [
                { name: "Technical Drawing", level: "Intermediate", category: "Technical", importance: "Important", timeToLearn: "3 months" },
                { name: "Mathematics", level: "Advanced", category: "Core", importance: "Critical", timeToLearn: "5 months" },
                { name: "Project Management", level: "Intermediate", category: "Management", importance: "Important", timeToLearn: "2 months" }
            ],
            business: [
                { name: "Business Analysis", level: "Advanced", category: "Analysis", importance: "Critical", timeToLearn: "4 months" },
                { name: "Communication", level: "Advanced", category: "Soft Skills", importance: "Critical", timeToLearn: "3 months" },
                { name: "Financial Literacy", level: "Intermediate", category: "Finance", importance: "Important", timeToLearn: "3 months" }
            ],
            arts: [
                { name: "Creative Thinking", level: "Advanced", category: "Core", importance: "Critical", timeToLearn: "4 months" },
                { name: "Visual Design", level: "Advanced", category: "Design", importance: "Critical", timeToLearn: "5 months" },
                { name: "Portfolio Development", level: "Intermediate", category: "Professional", importance: "Important", timeToLearn: "2 months" }
            ],
            law: [
                { name: "Legal Research", level: "Advanced", category: "Research", importance: "Critical", timeToLearn: "4 months" },
                { name: "Critical Analysis", level: "Advanced", category: "Analysis", importance: "Critical", timeToLearn: "4 months" },
                { name: "Writing Skills", level: "Advanced", category: "Communication", importance: "Critical", timeToLearn: "3 months" }
            ]
        };

        return commonSkills[domainKey] || [
            { name: "Critical Thinking", level: "Advanced", category: "Core", importance: "Critical", timeToLearn: "3 months" },
            { name: "Communication", level: "Intermediate", category: "Soft Skills", importance: "Important", timeToLearn: "2 months" }
        ];
    };

    // Get icon for career
    const getCareerIcon = (domain, careerName) => {
        if (domain === 'technology') return '💻';
        if (domain === 'science') return '🔬';
        if (domain === 'engineering') return '⚙️';
        if (domain === 'business') return '💼';
        if (domain === 'arts') return '🎨';
        if (domain === 'law') return '⚖️';
        if (domain === 'agriculture') return '🌾';
        if (domain === 'defense') return '🛡️';
        return '🎯';
    };

    // Get gradient colors for domain
    const getGradientForDomain = (domain) => {
        const gradients = {
            technology: 'from-blue-500 to-indigo-600',
            science: 'from-green-500 to-teal-600',
            engineering: 'from-orange-500 to-red-600',
            business: 'from-purple-500 to-pink-600',
            arts: 'from-pink-500 to-rose-600',
            law: 'from-gray-700 to-gray-900',
            agriculture: 'from-green-600 to-lime-600',
            defense: 'from-red-600 to-orange-700'
        };
        return gradients[domain] || 'from-cyan-500 to-blue-600';
    };

    // Generate skill requirements based on career type
    const generateSkillRequirements = (career, baseSkills, domainKey) => {
        const skills = [];

        // Add base skills from career data
        baseSkills.forEach((skill, index) => {
            skills.push({
                name: skill,
                level: index < 3 ? "Advanced" : index < 6 ? "Intermediate" : "Beginner",
                category: getCategoryForSkill(skill, domainKey),
                importance: index < 2 ? "Critical" : index < 5 ? "Important" : "Good to Have",
                timeToLearn: getTimeEstimate(index < 3 ? "Advanced" : index < 6 ? "Intermediate" : "Beginner")
            });
        });

        // Add domain-specific skills
        const domainSkills = getDomainSpecificSkills(domainKey, career.name);
        domainSkills.forEach(skill => {
            if (!skills.find(s => s.name === skill.name)) {
                skills.push(skill);
            }
        });

        return skills.slice(0, 10); // Limit to 10 skills per career
    };

    // Generate all careers from database with skill requirements
    const allCareers = useMemo(() => {
        const careers = [];

        Object.entries(CAREER_DATABASE).forEach(([domainKey, domain]) => {
            domain.subFields.forEach(subField => {
                subField.careers.forEach(career => {
                    // Generate skill requirements based on career skills
                    const baseSkills = career.skills || [];
                    const requiredSkills = generateSkillRequirements(career, baseSkills, domainKey);

                    careers.push({
                        id: `${domainKey}-${subField.id}-${career.name.replace(/\s+/g, '-').toLowerCase()}`,
                        name: career.name,
                        icon: getCareerIcon(domainKey, career.name),
                        salary: career.salaryRange,
                        demand: career.jobOutlook,
                        domain: domain.name,
                        domainKey: domainKey,
                        color: getGradientForDomain(domainKey),
                        description: career.description,
                        requiredSkills: requiredSkills
                    });
                });
            });
        });

        return careers;
    }, []);

    // Filter careers based on search and domain
    const filteredCareers = allCareers.filter(career => {
        const matchesSearch = career.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            career.description.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesDomain = selectedDomain === 'all' || career.domainKey === selectedDomain;
        return matchesSearch && matchesDomain;
    });

    // Get unique domains for filter
    const domains = useMemo(() => {
        const uniqueDomains = [...new Set(allCareers.map(c => ({ key: c.domainKey, name: c.domain })))];
        return uniqueDomains.filter((domain, index, self) =>
            index === self.findIndex((d) => d.key === domain.key)
        );
    }, [allCareers]);

    // Handle career selection
    const handleCareerSelect = (career) => {
        setSelectedCareer(career);
        setCurrentSkills([]);
        setSkillLevels({});
        setStep(2);
    };

    // Handle skill selection
    const handleSkillToggle = (skillName) => {
        if (currentSkills.includes(skillName)) {
            setCurrentSkills(currentSkills.filter(s => s !== skillName));
            const newLevels = { ...skillLevels };
            delete newLevels[skillName];
            setSkillLevels(newLevels);
        } else {
            setCurrentSkills([...currentSkills, skillName]);
            setSkillLevels({ ...skillLevels, [skillName]: 'Beginner' });
        }
    };

    // Generate analysis
    const generateAnalysis = () => {
        const requiredSkills = selectedCareer.requiredSkills;

        // Calculate gaps
        const criticalGaps = requiredSkills.filter(skill =>
            skill.importance === 'Critical' && !currentSkills.includes(skill.name)
        );

        const importantGaps = requiredSkills.filter(skill =>
            skill.importance === 'Important' && !currentSkills.includes(skill.name)
        );

        const goodToHaveGaps = requiredSkills.filter(skill =>
            skill.importance === 'Good to Have' && !currentSkills.includes(skill.name)
        );

        // Calculate readiness score
        const totalRequired = requiredSkills.filter(s => s.importance === 'Critical' || s.importance === 'Important').length;
        const acquired = currentSkills.filter(skill => {
            const reqSkill = requiredSkills.find(s => s.name === skill);
            return reqSkill && (reqSkill.importance === 'Critical' || reqSkill.importance === 'Important');
        }).length;
        const readinessScore = Math.round((acquired / totalRequired) * 100);

        // Calculate time to ready
        const totalMonths = [...criticalGaps, ...importantGaps].reduce((sum, skill) => {
            return sum + parseFloat(skill.timeToLearn);
        }, 0);

        // Generate learning path (prioritized)
        const learningPath = [
            ...criticalGaps.sort((a, b) => parseFloat(a.timeToLearn) - parseFloat(b.timeToLearn)),
            ...importantGaps.sort((a, b) => parseFloat(a.timeToLearn) - parseFloat(b.timeToLearn)),
            ...goodToHaveGaps.sort((a, b) => parseFloat(a.timeToLearn) - parseFloat(b.timeToLearn))
        ];

        // Skills you have at right level
        const matchingSkills = currentSkills.filter(skill => {
            const reqSkill = requiredSkills.find(s => s.name === skill);
            return reqSkill && (
                (skillLevels[skill] === 'Advanced' && reqSkill.level === 'Advanced') ||
                (skillLevels[skill] === 'Intermediate' && (reqSkill.level === 'Intermediate' || reqSkill.level === 'Beginner')) ||
                (skillLevels[skill] === 'Beginner' && reqSkill.level === 'Beginner')
            );
        });

        // Skills you have but need to improve
        const skillsToImprove = currentSkills.filter(skill => {
            const reqSkill = requiredSkills.find(s => s.name === skill);
            if (!reqSkill) return false;

            const currentLevel = skillLevels[skill];
            const requiredLevel = reqSkill.level;

            if (requiredLevel === 'Advanced' && currentLevel !== 'Advanced') return true;
            if (requiredLevel === 'Intermediate' && currentLevel === 'Beginner') return true;
            return false;
        });

        setAnalysis({
            readinessScore,
            criticalGaps,
            importantGaps,
            goodToHaveGaps,
            totalMonths: Math.round(totalMonths),
            learningPath,
            matchingSkills,
            skillsToImprove
        });

        setStep(3);
    };

    return (
        <div className={`fixed inset-0 z-50 overflow-y-auto ${darkMode ? 'bg-[#0f1419]' : 'bg-gradient-to-br from-slate-50 to-indigo-50'
            }`}>
            <div className="max-w-7xl mx-auto px-4 py-8">
                {/* Header */}
                <div className="flex items-center justify-between mb-8">
                    <div>
                        <h2 className={`text-4xl font-black ${darkMode ? 'text-white' : 'text-gray-900'} mb-2`}>
                            🎯 AI Skills Gap Analyzer
                        </h2>
                        <p className={`text-lg ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                            Analyze your skills vs career requirements • Get personalized roadmap
                        </p>
                    </div>
                    <button
                        onClick={onClose}
                        className={`p-2 rounded-xl transition-colors ${darkMode ? 'bg-[#1a1f2e] hover:bg-[#272757]' : 'bg-white hover:bg-gray-100'
                            }`}
                    >
                        <X className={`w-6 h-6 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`} />
                    </button>
                </div>

                {/* Progress Steps */}
                <div className="flex items-center justify-center mb-12">
                    <div className="flex items-center gap-4">
                        <div className={`flex items-center gap-2 px-4 py-2 rounded-full ${step >= 1
                            ? darkMode ? 'bg-[#505081] text-white' : 'bg-indigo-600 text-white'
                            : darkMode ? 'bg-[#272757] text-gray-500' : 'bg-gray-200 text-gray-400'
                            }`}>
                            <Target className="w-4 h-4" />
                            <span className="font-semibold">Select Career</span>
                        </div>
                        <div className={`w-8 h-0.5 ${step >= 2 ? 'bg-indigo-600' : 'bg-gray-300'}`}></div>
                        <div className={`flex items-center gap-2 px-4 py-2 rounded-full ${step >= 2
                            ? darkMode ? 'bg-[#505081] text-white' : 'bg-indigo-600 text-white'
                            : darkMode ? 'bg-[#272757] text-gray-500' : 'bg-gray-200 text-gray-400'
                            }`}>
                            <Brain className="w-4 h-4" />
                            <span className="font-semibold">Your Skills</span>
                        </div>
                        <div className={`w-8 h-0.5 ${step >= 3 ? 'bg-indigo-600' : 'bg-gray-300'}`}></div>
                        <div className={`flex items-center gap-2 px-4 py-2 rounded-full ${step >= 3
                            ? darkMode ? 'bg-[#505081] text-white' : 'bg-indigo-600 text-white'
                            : darkMode ? 'bg-[#272757] text-gray-500' : 'bg-gray-200 text-gray-400'
                            }`}>
                            <BarChart3 className="w-4 h-4" />
                            <span className="font-semibold">Analysis</span>
                        </div>
                    </div>
                </div>

                {/* Step 1: Career Selection */}
                {step === 1 && (
                    <div>
                        <div className="text-center mb-8">
                            <h3 className={`text-2xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'} mb-2`}>
                                What career are you aiming for?
                            </h3>
                            <p className={`${darkMode ? 'text-gray-400' : 'text-gray-600'} mb-4`}>
                                Choose from {allCareers.length}+ careers to analyze your skill gaps
                            </p>

                            {/* Search and Filter */}
                            <div className="flex flex-col sm:flex-row gap-4 max-w-4xl mx-auto">
                                {/* Search */}
                                <div className="flex-1 relative">
                                    <Search className={`absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 ${darkMode ? 'text-gray-500' : 'text-gray-400'
                                        }`} />
                                    <input
                                        type="text"
                                        placeholder="Search careers..."
                                        value={searchQuery}
                                        onChange={(e) => setSearchQuery(e.target.value)}
                                        className={`w-full pl-10 pr-4 py-3 rounded-xl border-2 transition-colors ${darkMode
                                            ? 'bg-[#1a1f2e] border-[#272757] text-white placeholder-gray-500 focus:border-[#8686AC]'
                                            : 'bg-white border-gray-200 text-gray-900 placeholder-gray-400 focus:border-indigo-500'
                                            } focus:outline-none`}
                                    />
                                </div>

                                {/* Domain Filter */}
                                <select
                                    value={selectedDomain}
                                    onChange={(e) => setSelectedDomain(e.target.value)}
                                    className={`px-4 py-3 rounded-xl border-2 font-semibold ${darkMode
                                        ? 'bg-[#1a1f2e] border-[#272757] text-white'
                                        : 'bg-white border-gray-200 text-gray-900'
                                        } focus:outline-none focus:border-indigo-500`}
                                >
                                    <option value="all">All Domains</option>
                                    {domains.map(domain => (
                                        <option key={domain.key} value={domain.key}>
                                            {domain.name}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        {/* Results Count */}
                        <div className={`text-center mb-6 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                            Showing {filteredCareers.length} career{filteredCareers.length !== 1 ? 's' : ''}
                        </div>

                        {/* Career Cards */}
                        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {filteredCareers.length > 0 ? (
                                filteredCareers.map((career) => (
                                    <button
                                        key={career.id}
                                        onClick={() => handleCareerSelect(career)}
                                        className={`group relative rounded-2xl p-6 text-left transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl overflow-hidden ${darkMode ? 'bg-[#1a1f2e] border border-[#272757]' : 'bg-white border border-indigo-100'
                                            }`}
                                    >
                                        <div className={`absolute inset-0 opacity-0 group-hover:opacity-10 transition-opacity bg-gradient-to-br ${career.color}`}></div>

                                        <div className="relative z-10">
                                            <div className="flex items-start justify-between mb-3">
                                                <div className="text-5xl">{career.icon}</div>
                                                <div className={`text-xs px-2 py-1 rounded ${darkMode ? 'bg-[#272757] text-gray-400' : 'bg-gray-100 text-gray-600'
                                                    }`}>
                                                    {career.domain}
                                                </div>
                                            </div>
                                            <h3 className={`text-lg font-bold mb-2 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                                {career.name}
                                            </h3>
                                            <p className={`text-sm mb-3 line-clamp-2 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                                {career.description}
                                            </p>
                                            <div className="space-y-2">
                                                <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                                    💰 {career.salary}
                                                </div>
                                                <div className={`text-xs font-semibold ${darkMode ? 'text-[#8686AC]' : 'text-indigo-600'}`}>
                                                    {career.requiredSkills.length} skills required →
                                                </div>
                                            </div>
                                        </div>
                                    </button>
                                ))
                            ) : (
                                <div className={`col-span-full text-center py-12 ${darkMode ? 'text-gray-500' : 'text-gray-400'}`}>
                                    <p className="text-lg mb-2">No careers found</p>
                                    <p className="text-sm">Try adjusting your search or filter</p>
                                </div>
                            )}
                        </div>
                    </div>
                )}

                {/* Step 2: Current Skills */}
                {step === 2 && selectedCareer && (
                    <div>
                        <div className="flex items-center justify-between mb-8">
                            <div>
                                <h3 className={`text-2xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'} mb-2`}>
                                    Select skills you currently have
                                </h3>
                                <p className={`${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                    Check all that apply and set your proficiency level
                                </p>
                            </div>
                            <button
                                onClick={() => setStep(1)}
                                className={`px-4 py-2 rounded-xl font-semibold ${darkMode ? 'bg-[#272757] text-white' : 'bg-gray-200 text-gray-700'
                                    }`}
                            >
                                ← Back
                            </button>
                        </div>

                        <div className={`rounded-2xl p-6 mb-6 ${darkMode ? 'bg-[#1a1f2e] border border-[#272757]' : 'bg-white border border-indigo-100'
                            }`}>
                            <div className="flex items-center gap-4 mb-4">
                                <div className="text-5xl">{selectedCareer.icon}</div>
                                <div>
                                    <h4 className={`text-xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                        {selectedCareer.name}
                                    </h4>
                                    <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                        {selectedCareer.requiredSkills.length} required skills
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div className="grid md:grid-cols-2 gap-4 mb-8">
                            {selectedCareer.requiredSkills.map((skill) => (
                                <div
                                    key={skill.name}
                                    className={`p-4 rounded-xl border-2 transition-all ${currentSkills.includes(skill.name)
                                        ? darkMode
                                            ? 'bg-[#505081] border-[#8686AC]'
                                            : 'bg-indigo-50 border-indigo-500'
                                        : darkMode
                                            ? 'bg-[#1a1f2e] border-[#272757] hover:border-[#505081]'
                                            : 'bg-white border-gray-200 hover:border-indigo-300'
                                        }`}
                                >
                                    <div className="flex items-start gap-3">
                                        <button
                                            onClick={() => handleSkillToggle(skill.name)}
                                            className={`flex-shrink-0 w-6 h-6 rounded-md border-2 flex items-center justify-center ${currentSkills.includes(skill.name)
                                                ? 'bg-indigo-600 border-indigo-600'
                                                : darkMode ? 'border-gray-600' : 'border-gray-300'
                                                }`}
                                        >
                                            {currentSkills.includes(skill.name) && (
                                                <CheckCircle className="w-4 h-4 text-white" />
                                            )}
                                        </button>
                                        <div className="flex-1">
                                            <div className="flex items-center justify-between mb-1">
                                                <h4 className={`font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                                    {skill.name}
                                                </h4>
                                                <span className={`text-xs px-2 py-0.5 rounded ${skill.importance === 'Critical'
                                                    ? 'bg-red-100 text-red-700'
                                                    : skill.importance === 'Important'
                                                        ? 'bg-yellow-100 text-yellow-700'
                                                        : 'bg-gray-100 text-gray-600'
                                                    }`}>
                                                    {skill.importance}
                                                </span>
                                            </div>
                                            <p className={`text-xs mb-2 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                                Required: {skill.level} • {skill.category}
                                            </p>

                                            {currentSkills.includes(skill.name) && (
                                                <select
                                                    value={skillLevels[skill.name] || 'Beginner'}
                                                    onChange={(e) => setSkillLevels({ ...skillLevels, [skill.name]: e.target.value })}
                                                    className={`w-full px-3 py-1.5 rounded-lg text-sm ${darkMode
                                                        ? 'bg-[#272757] text-white border border-[#505081]'
                                                        : 'bg-gray-50 text-gray-900 border border-gray-200'
                                                        }`}
                                                >
                                                    <option value="Beginner">Beginner</option>
                                                    <option value="Intermediate">Intermediate</option>
                                                    <option value="Advanced">Advanced</option>
                                                </select>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>

                        <div className="flex justify-end">
                            <button
                                onClick={generateAnalysis}
                                disabled={currentSkills.length === 0}
                                className={`px-8 py-3 rounded-xl font-bold transition-all flex items-center gap-2 ${currentSkills.length > 0
                                    ? darkMode
                                        ? 'bg-gradient-to-r from-[#505081] to-[#8686AC] hover:from-[#8686AC] hover:to-[#505081] text-white'
                                        : 'bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white'
                                    : darkMode
                                        ? 'bg-[#272757] text-gray-600 cursor-not-allowed'
                                        : 'bg-gray-200 text-gray-400 cursor-not-allowed'
                                    }`}
                            >
                                <Sparkles className="w-5 h-5" />
                                Analyze Skills Gap
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 3: Analysis & Roadmap */}
                {step === 3 && analysis && (
                    <div>
                        <div className="flex items-center justify-between mb-8">
                            <div>
                                <h3 className={`text-2xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'} mb-2`}>
                                    Your Personalized Learning Roadmap
                                </h3>
                                <p className={`${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                    AI-generated path to become a {selectedCareer.name}
                                </p>
                            </div>
                            <button
                                onClick={() => setStep(1)}
                                className={`px-4 py-2 rounded-xl font-semibold ${darkMode ? 'bg-[#272757] text-white' : 'bg-gray-200 text-gray-700'
                                    }`}
                            >
                                ↻ Start Over
                            </button>
                        </div>

                        {/* Readiness Score */}
                        <div className={`rounded-2xl p-8 mb-8 ${darkMode
                            ? 'bg-gradient-to-br from-[#272757] to-[#505081]'
                            : 'bg-gradient-to-br from-indigo-500 to-purple-500'
                            }`}>
                            <div className="text-center">
                                <div className="text-7xl font-black text-white mb-2">
                                    {analysis.readinessScore}%
                                </div>
                                <div className="text-xl text-white/90 font-semibold mb-4">
                                    Career Readiness Score
                                </div>
                                <div className="grid md:grid-cols-3 gap-4">
                                    <div className="text-center">
                                        <div className="text-3xl font-bold text-white mb-1">
                                            {analysis.matchingSkills.length}
                                        </div>
                                        <div className="text-white/80 text-sm">Skills Acquired</div>
                                    </div>
                                    <div className="text-center">
                                        <div className="text-3xl font-bold text-white mb-1">
                                            {analysis.criticalGaps.length + analysis.importantGaps.length}
                                        </div>
                                        <div className="text-white/80 text-sm">Skills to Learn</div>
                                    </div>
                                    <div className="text-center">
                                        <div className="text-3xl font-bold text-white mb-1">
                                            {analysis.totalMonths}
                                        </div>
                                        <div className="text-white/80 text-sm">Months to Ready</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="grid lg:grid-cols-2 gap-6 mb-8">
                            {/* Skills You Have */}
                            <div className={`rounded-2xl p-6 ${darkMode ? 'bg-[#1a1f2e] border border-[#272757]' : 'bg-white border border-indigo-100'
                                }`}>
                                <div className="flex items-center gap-2 mb-4">
                                    <CheckCircle className="w-5 h-5 text-green-500" />
                                    <h4 className={`text-lg font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                        ✅ Skills You Have ({analysis.matchingSkills.length})
                                    </h4>
                                </div>
                                <div className="space-y-2">
                                    {analysis.matchingSkills.map((skillName) => {
                                        const skill = selectedCareer.requiredSkills.find(s => s.name === skillName);
                                        return (
                                            <div key={skillName} className={`p-3 rounded-lg ${darkMode ? 'bg-green-900/20' : 'bg-green-50'
                                                }`}>
                                                <div className="flex items-center justify-between">
                                                    <span className={`font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                                        {skillName}
                                                    </span>
                                                    <span className={`text-xs px-2 py-1 rounded ${darkMode ? 'bg-green-900/40 text-green-400' : 'bg-green-200 text-green-700'
                                                        }`}>
                                                        {skillLevels[skillName]}
                                                    </span>
                                                </div>
                                                <p className={`text-xs mt-1 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                                    {skill?.category}
                                                </p>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Skills to Improve */}
                            {analysis.skillsToImprove.length > 0 && (
                                <div className={`rounded-2xl p-6 ${darkMode ? 'bg-[#1a1f2e] border border-[#272757]' : 'bg-white border border-indigo-100'
                                    }`}>
                                    <div className="flex items-center gap-2 mb-4">
                                        <TrendingUp className="w-5 h-5 text-yellow-500" />
                                        <h4 className={`text-lg font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                            📈 Skills to Improve ({analysis.skillsToImprove.length})
                                        </h4>
                                    </div>
                                    <div className="space-y-2">
                                        {analysis.skillsToImprove.map((skillName) => {
                                            const skill = selectedCareer.requiredSkills.find(s => s.name === skillName);
                                            return (
                                                <div key={skillName} className={`p-3 rounded-lg ${darkMode ? 'bg-yellow-900/20' : 'bg-yellow-50'
                                                    }`}>
                                                    <div className="flex items-center justify-between">
                                                        <span className={`font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                                            {skillName}
                                                        </span>
                                                        <div className="flex items-center gap-2">
                                                            <span className="text-xs px-2 py-1 rounded bg-gray-200 text-gray-700">
                                                                {skillLevels[skillName]}
                                                            </span>
                                                            <span>→</span>
                                                            <span className="text-xs px-2 py-1 rounded bg-green-200 text-green-700">
                                                                {skill?.level}
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            );
                                        })}
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* Learning Roadmap */}
                        <div className={`rounded-2xl p-6 ${darkMode ? 'bg-[#1a1f2e] border border-[#272757]' : 'bg-white border border-indigo-100'
                            }`}>
                            <div className="flex items-center justify-between mb-6">
                                <div className="flex items-center gap-2">
                                    <Book className={`w-5 h-5 ${darkMode ? 'text-[#8686AC]' : 'text-indigo-600'}`} />
                                    <h4 className={`text-xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                        🎓 Your Personalized Learning Path
                                    </h4>
                                </div>
                                <button
                                    onClick={handleExportPDF}
                                    className={`px-4 py-2 rounded-xl font-semibold flex items-center gap-2 ${darkMode ? 'bg-[#505081] hover:bg-[#8686AC] text-white' : 'bg-indigo-100 hover:bg-indigo-200 text-indigo-700'
                                        }`}>
                                    <Download className="w-4 h-4" />
                                    Export PDF
                                </button>
                            </div>

                            <div className="space-y-4">
                                {analysis.learningPath.map((skill, index) => (
                                    <div
                                        key={skill.name}
                                        className={`p-4 rounded-xl border-2 ${darkMode ? 'bg-[#272757] border-[#505081]' : 'bg-gray-50 border-gray-200'
                                            }`}
                                    >
                                        <div className="flex items-start gap-4">
                                            <div className={`flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center font-bold text-white ${skill.importance === 'Critical'
                                                ? 'bg-red-500'
                                                : skill.importance === 'Important'
                                                    ? 'bg-yellow-500'
                                                    : 'bg-gray-500'
                                                }`}>
                                                {index + 1}
                                            </div>
                                            <div className="flex-1">
                                                <div className="flex items-center justify-between mb-2">
                                                    <h5 className={`font-bold text-lg ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                                        {skill.name}
                                                    </h5>
                                                    <div className="flex items-center gap-2">
                                                        <span className={`text-xs px-2 py-1 rounded ${skill.importance === 'Critical'
                                                            ? 'bg-red-100 text-red-700'
                                                            : skill.importance === 'Important'
                                                                ? 'bg-yellow-100 text-yellow-700'
                                                                : 'bg-gray-100 text-gray-600'
                                                            }`}>
                                                            {skill.importance}
                                                        </span>
                                                        <span className={`text-xs px-2 py-1 rounded ${darkMode ? 'bg-[#505081] text-[#8686AC]' : 'bg-indigo-100 text-indigo-700'
                                                            }`}>
                                                            {skill.level} Level
                                                        </span>
                                                    </div>
                                                </div>
                                                <div className="grid grid-cols-3 gap-4 mb-3">
                                                    <div>
                                                        <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                                            Category
                                                        </div>
                                                        <div className={`font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                                            {skill.category}
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                                            Time to Learn
                                                        </div>
                                                        <div className={`font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                                                            <Clock className="w-4 h-4 inline mr-1" />
                                                            {skill.timeToLearn}
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                                                            Priority
                                                        </div>
                                                        <div className={`font-semibold ${skill.importance === 'Critical' ? 'text-red-500' :
                                                            skill.importance === 'Important' ? 'text-yellow-500' :
                                                                'text-gray-500'
                                                            }`}>
                                                            {skill.importance === 'Critical' ? 'High' :
                                                                skill.importance === 'Important' ? 'Medium' : 'Low'}
                                                        </div>
                                                    </div>
                                                </div>
                                                <button
                                                    onClick={() => handleStartLearning(skill.name)}
                                                    className={`w-full px-4 py-2 rounded-lg font-semibold flex items-center justify-center gap-2 transition-colors ${darkMode
                                                        ? 'bg-[#505081] hover:bg-[#8686AC] text-white'
                                                        : 'bg-indigo-600 hover:bg-indigo-700 text-white'
                                                        }`}>
                                                    <Play className="w-4 h-4" />
                                                    Start Learning
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Action Buttons */}
                        <div className="flex gap-4 mt-8">
                            <button
                                onClick={handleEmailRoadmap}
                                className={`flex-1 px-6 py-3 rounded-xl font-bold transition-colors ${darkMode
                                    ? 'bg-gradient-to-r from-[#505081] to-[#8686AC] hover:from-[#8686AC] hover:to-[#505081] text-white'
                                    : 'bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white'
                                    }`}>
                                📧 Email This Roadmap
                            </button>
                            <button
                                onClick={handleSaveForLater}
                                className={`flex-1 px-6 py-3 rounded-xl font-bold transition-colors ${darkMode ? 'bg-[#272757] hover:bg-[#505081] text-white' : 'bg-gray-200 hover:bg-gray-300 text-gray-700'
                                    }`}>
                                💾 Save for Later
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default SkillsGapAnalyzer;