import React, { useState, useMemo } from 'react';
import { X, Target, TrendingUp, Book, Award, Clock, CheckCircle, Brain, Zap, BarChart3, AlertCircle, Sparkles, Play, Download, Search, CheckCircle2 } from 'lucide-react';
import { CAREER_DATABASE } from '../data/careerDatabase';

const SkillsGapAnalyzer = ({ onClose, darkMode }) => {
    const [step, setStep] = useState(1); // 1: Career selection, 2: Current skills, 3: Analysis & Roadmap
    const [selectedCareer, setSelectedCareer] = useState(null);
    const [currentSkills, setCurrentSkills] = useState([]);
    const [skillLevels, setSkillLevels] = useState({});
    const [analysis, setAnalysis] = useState(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [selectedDomain, setSelectedDomain] = useState('all');

    // Handler functions for buttons
    const handleStartLearning = (skillName) => {
        alert(`🎓 Starting learning resources for: ${skillName}\n\nRecommended platforms:\n• Coursera\n• Udemy\n• Khan Academy\n• YouTube\n• FreeCodeCamp`);
    };

    const handleExportPDF = () => {
        const content = `
CAREER READINESS REPORT
========================

Career: ${selectedCareer.name}
Readiness Score: ${analysis.readinessScore}%

SKILLS ACQUIRED (${analysis.matchingSkills.length}):
${analysis.matchingSkills.map((s, i) => `${i + 1}. ${s}`).join('\n')}

LEARNING ROADMAP (${analysis.learningPath.length} skills):
${analysis.learningPath.map((skill, i) => `
${i + 1}. ${skill.name}
   Level: ${skill.level}
   Category: ${skill.category}
   Priority: ${skill.importance}
   Time: ${skill.timeToLearn}
`).join('\n')}

Generated by COGNITRAIL Skills Gap Analyzer
    `.trim();

        // Create blob and download
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${selectedCareer.name.replace(/\s+/g, '_')}_Learning_Roadmap.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        alert('✅ Learning roadmap exported successfully!');
    };

    const handleEmailRoadmap = () => {
        const subject = encodeURIComponent(`My ${selectedCareer.name} Learning Roadmap`);
        const body = encodeURIComponent(`
Hi,

I've created a personalized learning roadmap for becoming a ${selectedCareer.name}.

Career Readiness Score: ${analysis.readinessScore}%
Skills to Learn: ${analysis.learningPath.length}
Estimated Time: ${analysis.totalMonths} months

Top Priority Skills:
${analysis.learningPath.slice(0, 5).map((skill, i) => `${i + 1}. ${skill.name} (${skill.timeToLearn})`).join('\n')}

Created with COGNITRAIL Skills Gap Analyzer.

Best regards
    `);

        window.location.href = `mailto:?subject=${subject}&body=${body}`;
    };

    const handleSaveForLater = () => {
        const roadmapData = {
            career: selectedCareer.name,
            readinessScore: analysis.readinessScore,
            matchingSkills: analysis.matchingSkills,
            learningPath: analysis.learningPath,
            totalMonths: analysis.totalMonths,
            savedAt: new Date().toISOString()
        };

        // Save to localStorage
        const savedRoadmaps = JSON.parse(localStorage.getItem('savedRoadmaps') || '[]');
        savedRoadmaps.push(roadmapData);
        localStorage.setItem('savedRoadmaps', JSON.stringify(savedRoadmaps));

        alert('✅ Roadmap saved successfully!\n\nYou can access it anytime from your saved roadmaps.');
    };

    // Get category for a skill
    const getCategoryForSkill = (skill, domain) => {
        const skillLower = skill.toLowerCase();

        if (skillLower.includes('programming') || skillLower.includes('coding') || skillLower.includes('software')) return 'Programming';
        if (skillLower.includes('design') || skillLower.includes('ui') || skillLower.includes('ux')) return 'Design';
        if (skillLower.includes('communication') || skillLower.includes('presentation')) return 'Soft Skills';
        if (skillLower.includes('analysis') || skillLower.includes('analytical')) return 'Analysis';
        if (skillLower.includes('management') || skillLower.includes('leadership')) return 'Management';
        if (skillLower.includes('medical') || skillLower.includes('clinical')) return 'Medical';
        if (skillLower.includes('research')) return 'Research';
        if (skillLower.includes('technical')) return 'Technical';

        return domain === 'technology' ? 'Technical' : domain === 'medical' ? 'Medical' : 'Core Skills';
    };

    // Get time estimate based on level
    const getTimeEstimate = (level) => {
        if (level === "Advanced") return `${3 + Math.floor(Math.random() * 3)} months`;
        if (level === "Intermediate") return `${2 + Math.floor(Math.random() * 2)} months`;
        return `${1 + Math.floor(Math.random() * 2)} months`;
    };

    // Get domain-specific additional skills
    const getDomainSpecificSkills = (domainKey, careerName) => {
        const skillsMap = {
            engineering: [
                { name: 'Data Structures & Algorithms', level: 'Intermediate', importance: 'Critical' },
                { name: 'System Design', level: 'Intermediate', importance: 'Important' },
                { name: 'Git & Version Control', level: 'Beginner', importance: 'Important' },
                { name: 'Cloud Computing (AWS/GCP)', level: 'Intermediate', importance: 'Nice to have' },
                { name: 'API Development & REST', level: 'Intermediate', importance: 'Important' }
            ],
            medical: [
                { name: 'Clinical Diagnostics', level: 'Advanced', importance: 'Critical' },
                { name: 'Medical Terminology & Pathology', level: 'Intermediate', importance: 'Critical' },
                { name: 'Patient Empathy & Care', level: 'Intermediate', importance: 'Important' },
                { name: 'Medical Ethics & Law', level: 'Intermediate', importance: 'Important' },
                { name: 'Emergency Protocol Handling', level: 'Advanced', importance: 'Critical' }
            ],
            business: [
                { name: 'Financial Modeling & Valuation', level: 'Intermediate', importance: 'Critical' },
                { name: 'Market Research & Analytics', level: 'Intermediate', importance: 'Important' },
                { name: 'Strategic Negotiation', level: 'Intermediate', importance: 'Important' },
                { name: 'Business Presentation', level: 'Intermediate', importance: 'Critical' },
                { name: 'Project & Team Management', level: 'Intermediate', importance: 'Important' }
            ],
            creative: [
                { name: 'User Research & Personas', level: 'Intermediate', importance: 'Critical' },
                { name: 'Figma / Visual Prototyping', level: 'Intermediate', importance: 'Critical' },
                { name: 'Typography & Layout Systems', level: 'Intermediate', importance: 'Important' },
                { name: 'Design Systems Architecture', level: 'Intermediate', importance: 'Important' },
                { name: 'Storyboarding & Motion Basics', level: 'Beginner', importance: 'Nice to have' }
            ]
        };

        return skillsMap[domainKey] || [
            { name: 'Critical Problem Solving', level: 'Intermediate', importance: 'Critical' },
            { name: 'Cross-functional Communication', level: 'Intermediate', importance: 'Critical' },
            { name: 'Data Analysis & Insights', level: 'Beginner', importance: 'Important' },
            { name: 'Project Milestone Tracking', level: 'Beginner', importance: 'Important' }
        ];
    };

    // Extract all careers from CAREER_DATABASE
    const allCareers = useMemo(() => {
        const careers = [];
        let idCounter = 1;

        Object.entries(CAREER_DATABASE).forEach(([domainKey, domain]) => {
            domain.subFields.forEach(subField => {
                subField.careers.forEach(career => {
                    const baseSkills = (career.skills || []).map((skillName, idx) => ({
                        name: skillName,
                        level: idx < 2 ? 'Intermediate' : idx < 4 ? 'Advanced' : 'Beginner',
                        category: getCategoryForSkill(skillName, domainKey),
                        importance: idx < 2 ? 'Critical' : idx < 5 ? 'Important' : 'Nice to have',
                        timeToLearn: getTimeEstimate(idx < 2 ? 'Intermediate' : 'Beginner')
                    }));

                    const domainSkills = getDomainSpecificSkills(domainKey, career.name).map(skill => ({
                        ...skill,
                        category: getCategoryForSkill(skill.name, domainKey),
                        timeToLearn: getTimeEstimate(skill.level)
                    }));

                    const combinedSkills = [...baseSkills];
                    domainSkills.forEach(ds => {
                        if (!combinedSkills.some(cs => cs.name.toLowerCase() === ds.name.toLowerCase())) {
                            combinedSkills.push(ds);
                        }
                    });

                    careers.push({
                        id: `career-${idCounter++}`,
                        name: career.name,
                        domain: domain.name,
                        domainKey: domainKey,
                        icon: domain.icon,
                        description: career.description,
                        salary: career.salaryRange,
                        requiredSkills: combinedSkills
                    });
                });
            });
        });

        return careers;
    }, []);

    // Extract domains for filter
    const domains = useMemo(() => {
        return Object.entries(CAREER_DATABASE).map(([key, domain]) => ({
            key: key,
            name: domain.name,
            icon: domain.icon
        }));
    }, []);

    // Filter careers based on search and domain
    const filteredCareers = useMemo(() => {
        return allCareers.filter(career => {
            const matchesSearch = career.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                career.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
                career.requiredSkills.some(s => s.name.toLowerCase().includes(searchQuery.toLowerCase()));

            const matchesDomain = selectedDomain === 'all' || career.domainKey === selectedDomain;

            return matchesSearch && matchesDomain;
        });
    }, [allCareers, searchQuery, selectedDomain]);

    // Handle career selection
    const handleCareerSelect = (career) => {
        setSelectedCareer(career);
        setCurrentSkills([]);
        setSkillLevels({});
        setStep(2);
    };

    // Handle skill toggle
    const handleSkillToggle = (skillName) => {
        if (currentSkills.includes(skillName)) {
            setCurrentSkills(currentSkills.filter(s => s !== skillName));
            const newLevels = { ...skillLevels };
            delete newLevels[skillName];
            setSkillLevels(newLevels);
        } else {
            setCurrentSkills([...currentSkills, skillName]);
            setSkillLevels({ ...skillLevels, [skillName]: 'Beginner' });
        }
    };

    // Generate skills gap analysis
    const generateAnalysis = () => {
        if (!selectedCareer) return;

        const matchingSkills = [];
        const missingSkills = [];
        const skillsToImprove = [];
        let totalScore = 0;
        let maxScore = 0;

        selectedCareer.requiredSkills.forEach(reqSkill => {
            const weight = reqSkill.importance === 'Critical' ? 3 : reqSkill.importance === 'Important' ? 2 : 1;
            maxScore += weight * 3; // 3 is Advanced level

            if (currentSkills.includes(reqSkill.name)) {
                matchingSkills.push(reqSkill.name);
                const userLevel = skillLevels[reqSkill.name] || 'Beginner';
                const levelScore = userLevel === 'Advanced' ? 3 : userLevel === 'Intermediate' ? 2 : 1;
                totalScore += weight * levelScore;

                const reqLevelScore = reqSkill.level === 'Advanced' ? 3 : reqSkill.level === 'Intermediate' ? 2 : 1;
                if (levelScore < reqLevelScore) {
                    skillsToImprove.push(reqSkill.name);
                }
            } else {
                missingSkills.push(reqSkill);
            }
        });

        const readinessScore = Math.round((totalScore / maxScore) * 100);
        const criticalGaps = missingSkills.filter(s => s.importance === 'Critical');
        const importantGaps = missingSkills.filter(s => s.importance === 'Important');

        const learningPath = [
            ...criticalGaps,
            ...importantGaps,
            ...missingSkills.filter(s => s.importance === 'Nice to have')
        ];

        let totalMonths = 0;
        learningPath.forEach(skill => {
            const months = parseInt(skill.timeToLearn) || 2;
            totalMonths += months;
        });

        setAnalysis({
            readinessScore,
            matchingSkills,
            missingSkills,
            skillsToImprove,
            criticalGaps,
            importantGaps,
            learningPath,
            totalMonths: Math.ceil(totalMonths / 2) // Assuming parallel learning
        });

        setStep(3);
    };

    return (
        <div className={`fixed inset-0 z-50 overflow-y-auto ${darkMode ? 'bg-[#09090b]' : 'bg-zinc-50'}`}>
            <div className="max-w-7xl mx-auto px-4 py-8 animate-fade-in">
                {/* Header */}
                <div className="flex items-center justify-between mb-8">
                    <div>
                        <h2 className={`text-3xl font-black ${darkMode ? 'text-white' : 'text-black'} mb-2`}>
                            🎯 AI Skills Gap Analyzer
                        </h2>
                        <p className={`text-base sm:text-lg ${darkMode ? 'text-zinc-400' : 'text-zinc-600'}`}>
                            Analyze your current skills vs target career requirements • Get personalized roadmap
                        </p>
                    </div>
                    <button
                        onClick={onClose}
                        className={`p-2.5 rounded-xl border btn-interactive hover-lift ${darkMode ? 'bg-zinc-900 border-zinc-700 text-zinc-300 hover:text-white' : 'bg-white border-zinc-200 text-zinc-700 hover:text-black'}`}
                    >
                        <X className="w-6 h-6" />
                    </button>
                </div>

                {/* Progress Steps */}
                <div className="flex items-center justify-center mb-10">
                    <div className="flex items-center gap-3">
                        <div className={`flex items-center gap-2 px-4 py-2 rounded-full border text-xs font-bold ${step >= 1
                            ? darkMode ? 'bg-white text-black border-white' : 'bg-black text-white border-black'
                            : darkMode ? 'bg-zinc-900 text-zinc-500 border-zinc-800' : 'bg-zinc-100 text-zinc-400 border-zinc-200'
                            }`}>
                            <Target className="w-3.5 h-3.5" />
                            <span>1. Target Career</span>
                        </div>
                        <div className={`w-8 h-0.5 ${step >= 2 ? (darkMode ? 'bg-white' : 'bg-black') : (darkMode ? 'bg-zinc-800' : 'bg-zinc-300')}`}></div>
                        <div className={`flex items-center gap-2 px-4 py-2 rounded-full border text-xs font-bold ${step >= 2
                            ? darkMode ? 'bg-white text-black border-white' : 'bg-black text-white border-black'
                            : darkMode ? 'bg-zinc-900 text-zinc-500 border-zinc-800' : 'bg-zinc-100 text-zinc-400 border-zinc-200'
                            }`}>
                            <Brain className="w-3.5 h-3.5" />
                            <span>2. Your Skills</span>
                        </div>
                        <div className={`w-8 h-0.5 ${step >= 3 ? (darkMode ? 'bg-white' : 'bg-black') : (darkMode ? 'bg-zinc-800' : 'bg-zinc-300')}`}></div>
                        <div className={`flex items-center gap-2 px-4 py-2 rounded-full border text-xs font-bold ${step >= 3
                            ? darkMode ? 'bg-white text-black border-white' : 'bg-black text-white border-black'
                            : darkMode ? 'bg-zinc-900 text-zinc-500 border-zinc-800' : 'bg-zinc-100 text-zinc-400 border-zinc-200'
                            }`}>
                            <BarChart3 className="w-3.5 h-3.5" />
                            <span>3. Action Roadmap</span>
                        </div>
                    </div>
                </div>

                {/* Step 1: Career Selection */}
                {step === 1 && (
                    <div>
                        <div className="text-center mb-8">
                            <h3 className={`text-2xl font-black ${darkMode ? 'text-white' : 'text-black'} mb-2`}>
                                What target career are you aiming for?
                            </h3>
                            <p className={`text-sm ${darkMode ? 'text-zinc-400' : 'text-zinc-600'} mb-6`}>
                                Choose from {allCareers.length}+ careers to calculate your skill gaps
                            </p>

                            {/* Search and Filter */}
                            <div className="flex flex-col sm:flex-row gap-4 max-w-4xl mx-auto">
                                <div className="flex-1 relative">
                                    <Search className={`absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 ${darkMode ? 'text-zinc-500' : 'text-zinc-400'}`} />
                                    <input
                                        type="text"
                                        placeholder="Search careers or required skills..."
                                        value={searchQuery}
                                        onChange={(e) => setSearchQuery(e.target.value)}
                                        className={`w-full pl-10 pr-4 py-3 rounded-xl border text-sm transition-colors outline-none ${darkMode
                                            ? 'bg-[#18181b] border-zinc-700 text-white placeholder-zinc-500 focus:border-zinc-400'
                                            : 'bg-white border-zinc-200 text-black placeholder-zinc-400 focus:border-black'
                                            }`}
                                    />
                                </div>

                                <select
                                    value={selectedDomain}
                                    onChange={(e) => setSelectedDomain(e.target.value)}
                                    className={`px-4 py-3 rounded-xl border text-sm font-bold ${darkMode
                                        ? 'bg-[#18181b] border-zinc-700 text-white focus:border-zinc-400'
                                        : 'bg-white border-zinc-200 text-black focus:border-black'
                                        }`}
                                >
                                    <option value="all">All Domains</option>
                                    {domains.map(domain => (
                                        <option key={domain.key} value={domain.key}>
                                            {domain.name}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        {/* Career Cards Grid */}
                        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {filteredCareers.map((career) => (
                                <button
                                    key={career.id}
                                    onClick={() => handleCareerSelect(career)}
                                    className={`group relative rounded-3xl p-6 text-left border transition-all duration-300 hover-lift btn-interactive ${darkMode
                                        ? 'bg-[#121215] border-zinc-800 hover:border-zinc-600'
                                        : 'bg-white border-zinc-200 hover:border-zinc-400 shadow-sm'
                                        }`}
                                >
                                    <div className="flex items-start justify-between mb-3">
                                        <span className="text-3xl mb-1">{career.icon}</span>
                                        <span className={`text-xs px-2.5 py-1 rounded-full font-bold border ${darkMode ? 'bg-zinc-900 border-zinc-700 text-zinc-300' : 'bg-zinc-100 border-zinc-300 text-zinc-800'}`}>
                                            {career.domain}
                                        </span>
                                    </div>
                                    <h3 className={`text-lg font-black mb-2 transition-colors ${darkMode ? 'text-white group-hover:text-zinc-300' : 'text-black group-hover:text-zinc-700'}`}>
                                        {career.name}
                                    </h3>
                                    <p className={`text-xs mb-4 line-clamp-2 ${darkMode ? 'text-zinc-400' : 'text-zinc-600'}`}>
                                        {career.description}
                                    </p>
                                    <div className="pt-3 border-t border-zinc-100 dark:border-zinc-800 flex items-center justify-between text-xs font-bold">
                                        <span className={darkMode ? 'text-zinc-400' : 'text-zinc-600'}>{career.salary}</span>
                                        <span className={darkMode ? 'text-white' : 'text-black'}>{career.requiredSkills.length} skills required →</span>
                                    </div>
                                </button>
                            ))}
                        </div>
                    </div>
                )}

                {/* Step 2: Current Skills */}
                {step === 2 && selectedCareer && (
                    <div className="animate-fade-in">
                        <div className="flex items-center justify-between mb-8">
                            <div>
                                <h3 className={`text-2xl font-black ${darkMode ? 'text-white' : 'text-black'} mb-1`}>
                                    Select skills you currently have
                                </h3>
                                <p className={`text-sm ${darkMode ? 'text-zinc-400' : 'text-zinc-600'}`}>
                                    Check which skills you know and indicate your level
                                </p>
                            </div>
                            <button
                                onClick={() => setStep(1)}
                                className={`px-4 py-2 rounded-xl text-xs font-bold border btn-interactive ${darkMode ? 'bg-zinc-900 border-zinc-700 text-zinc-300' : 'bg-zinc-100 border-zinc-300 text-black'}`}
                            >
                                ← Choose Different Career
                            </button>
                        </div>

                        <div className={`rounded-3xl p-6 mb-6 border ${darkMode ? 'bg-[#121215] border-zinc-800' : 'bg-white border-zinc-200 shadow-sm'}`}>
                            <div className="flex items-center gap-4">
                                <span className="text-4xl">{selectedCareer.icon}</span>
                                <div>
                                    <h4 className={`text-xl font-black ${darkMode ? 'text-white' : 'text-black'}`}>
                                        {selectedCareer.name}
                                    </h4>
                                    <p className={`text-xs ${darkMode ? 'text-zinc-400' : 'text-zinc-600'}`}>
                                        Evaluating across {selectedCareer.requiredSkills.length} benchmark skills
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div className="grid md:grid-cols-2 gap-4 mb-8">
                            {selectedCareer.requiredSkills.map((skill) => {
                                const isSelected = currentSkills.includes(skill.name);
                                return (
                                    <div
                                        key={skill.name}
                                        className={`p-4 rounded-2xl border transition-all hover-lift ${isSelected
                                            ? darkMode ? 'bg-zinc-800 border-white text-white' : 'bg-zinc-100 border-black text-black'
                                            : darkMode ? 'bg-[#121215] border-zinc-800 text-zinc-300' : 'bg-white border-zinc-200 text-zinc-800'
                                            }`}
                                    >
                                        <div className="flex items-start gap-3">
                                            <button
                                                type="button"
                                                onClick={() => handleSkillToggle(skill.name)}
                                                className={`flex-shrink-0 w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all ${isSelected
                                                    ? darkMode ? 'bg-white border-white text-black' : 'bg-black border-black text-white'
                                                    : 'border-zinc-400 opacity-60'
                                                    }`}
                                            >
                                                {isSelected && <CheckCircle2 className="w-4 h-4" />}
                                            </button>
                                            <div className="flex-1">
                                                <div className="flex items-center justify-between mb-1">
                                                    <h4 className="font-bold text-sm">
                                                        {skill.name}
                                                    </h4>
                                                    <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-full border ${skill.importance === 'Critical'
                                                        ? 'bg-zinc-900 border-zinc-700 text-zinc-200'
                                                        : 'bg-zinc-100 dark:bg-zinc-800 border-zinc-300 dark:border-zinc-700 text-zinc-600 dark:text-zinc-400'
                                                        }`}>
                                                        {skill.importance}
                                                    </span>
                                                </div>
                                                <p className={`text-xs mb-2 ${darkMode ? 'text-zinc-400' : 'text-zinc-600'}`}>
                                                    Benchmark: {skill.level} • {skill.category}
                                                </p>

                                                {isSelected && (
                                                    <select
                                                        value={skillLevels[skill.name] || 'Beginner'}
                                                        onChange={(e) => setSkillLevels({ ...skillLevels, [skill.name]: e.target.value })}
                                                        className={`w-full px-3 py-1.5 rounded-xl text-xs font-bold border mt-2 ${darkMode
                                                            ? 'bg-zinc-900 border-zinc-700 text-white'
                                                            : 'bg-white border-zinc-300 text-black'
                                                            }`}
                                                    >
                                                        <option value="Beginner">Beginner Level</option>
                                                        <option value="Intermediate">Intermediate Level</option>
                                                        <option value="Advanced">Advanced Level</option>
                                                    </select>
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>

                        <div className="flex justify-end">
                            <button
                                onClick={generateAnalysis}
                                disabled={currentSkills.length === 0}
                                className={`px-8 py-4 rounded-2xl font-bold btn-interactive flex items-center gap-2 text-sm shadow-xl ${currentSkills.length > 0
                                    ? darkMode ? 'bg-white text-black hover:bg-zinc-200' : 'bg-black text-white hover:bg-zinc-800'
                                    : darkMode ? 'bg-zinc-800 text-zinc-600 cursor-not-allowed' : 'bg-zinc-200 text-zinc-400 cursor-not-allowed'
                                    }`}
                            >
                                <Sparkles className="w-5 h-5" />
                                Calculate Readiness Score & Roadmap
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 3: Analysis & Roadmap */}
                {step === 3 && analysis && (
                    <div className="animate-fade-in">
                        <div className="flex items-center justify-between mb-8">
                            <div>
                                <h3 className={`text-2xl font-black ${darkMode ? 'text-white' : 'text-black'} mb-1`}>
                                    Your Actionable Learning Roadmap
                                </h3>
                                <p className={`text-sm ${darkMode ? 'text-zinc-400' : 'text-zinc-600'}`}>
                                    Step-by-step pathway to qualify for {selectedCareer.name}
                                </p>
                            </div>
                            <button
                                onClick={() => setStep(1)}
                                className={`px-4 py-2 rounded-xl text-xs font-bold border btn-interactive ${darkMode ? 'bg-zinc-900 border-zinc-700 text-zinc-300' : 'bg-zinc-100 border-zinc-300 text-black'}`}
                            >
                                ↻ Analyze Another Career
                            </button>
                        </div>

                        {/* Readiness Score Card */}
                        <div className={`rounded-3xl p-8 mb-8 border ${darkMode ? 'bg-[#121215] border-zinc-800 text-white' : 'bg-black text-white'}`}>
                            <div className="text-center">
                                <div className="text-6xl font-black mb-2">
                                    {analysis.readinessScore}%
                                </div>
                                <div className="text-sm uppercase tracking-wider font-bold text-zinc-400 mb-6">
                                    Career Readiness Score
                                </div>
                                <div className="grid grid-cols-3 gap-4 pt-6 border-t border-zinc-800">
                                    <div>
                                        <div className="text-2xl font-black">{analysis.matchingSkills.length}</div>
                                        <div className="text-xs text-zinc-400">Skills Acquired</div>
                                    </div>
                                    <div>
                                        <div className="text-2xl font-black">{analysis.criticalGaps.length + analysis.importantGaps.length}</div>
                                        <div className="text-xs text-zinc-400">Skills to Master</div>
                                    </div>
                                    <div>
                                        <div className="text-2xl font-black">{analysis.totalMonths} mos</div>
                                        <div className="text-xs text-zinc-400">Est. Timeline</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Roadmap List */}
                        <div className={`rounded-3xl p-6 sm:p-8 mb-8 border ${darkMode ? 'bg-[#121215] border-zinc-800' : 'bg-white border-zinc-200 shadow-md'}`}>
                            <div className="flex items-center justify-between mb-6">
                                <div className="flex items-center gap-2">
                                    <Book className="w-5 h-5 text-zinc-400" />
                                    <h4 className={`text-lg font-black ${darkMode ? 'text-white' : 'text-black'}`}>
                                        Priority Learning Milestones
                                    </h4>
                                </div>
                                <button
                                    onClick={handleExportPDF}
                                    className={`px-4 py-2 rounded-xl text-xs font-bold border btn-interactive flex items-center gap-1.5 ${darkMode ? 'bg-zinc-900 border-zinc-700 text-zinc-300 hover:bg-white hover:text-black' : 'bg-zinc-100 border-zinc-300 text-black hover:bg-black hover:text-white'}`}
                                >
                                    <Download className="w-4 h-4" />
                                    Export Plan (.txt)
                                </button>
                            </div>

                            <div className="space-y-4">
                                {analysis.learningPath.map((skill, index) => (
                                    <div
                                        key={skill.name}
                                        className={`p-5 rounded-2xl border transition-all hover-lift ${darkMode ? 'bg-zinc-900/60 border-zinc-800' : 'bg-zinc-50 border-zinc-200'}`}
                                    >
                                        <div className="flex items-start gap-4">
                                            <div className={`w-8 h-8 rounded-xl flex items-center justify-center font-black text-xs ${darkMode ? 'bg-white text-black' : 'bg-black text-white'}`}>
                                                #{index + 1}
                                            </div>
                                            <div className="flex-1">
                                                <div className="flex items-center justify-between mb-2">
                                                    <h5 className={`font-black text-base ${darkMode ? 'text-white' : 'text-black'}`}>
                                                        {skill.name}
                                                    </h5>
                                                    <span className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full border ${darkMode ? 'bg-zinc-900 border-zinc-700 text-zinc-300' : 'bg-white border-zinc-300 text-black'}`}>
                                                        {skill.importance} Priority
                                                    </span>
                                                </div>
                                                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-xs mb-3 text-zinc-500 dark:text-zinc-400">
                                                    <div>Category: <span className="font-bold text-black dark:text-white">{skill.category}</span></div>
                                                    <div>Target: <span className="font-bold text-black dark:text-white">{skill.level}</span></div>
                                                    <div>Duration: <span className="font-bold text-black dark:text-white">{skill.timeToLearn}</span></div>
                                                </div>
                                                <button
                                                    onClick={() => handleStartLearning(skill.name)}
                                                    className={`w-full py-2.5 rounded-xl font-bold text-xs btn-interactive flex items-center justify-center gap-1.5 border ${darkMode ? 'bg-white text-black hover:bg-zinc-200' : 'bg-black text-white hover:bg-zinc-800'}`}
                                                >
                                                    <Play className="w-3.5 h-3.5" />
                                                    Explore Curated Learning Materials
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Action Buttons */}
                        <div className="flex flex-col sm:flex-row gap-4">
                            <button
                                onClick={handleEmailRoadmap}
                                className={`flex-1 py-4 rounded-2xl font-bold text-xs btn-interactive border ${darkMode ? 'bg-zinc-900 border-zinc-700 text-zinc-300 hover:text-white' : 'bg-white border-zinc-300 text-black hover:bg-zinc-100'}`}
                            >
                                📧 Email Roadmap To Myself
                            </button>
                            <button
                                onClick={handleSaveForLater}
                                className={`flex-1 py-4 rounded-2xl font-bold text-xs btn-interactive shadow-xl ${darkMode ? 'bg-white text-black hover:bg-zinc-200' : 'bg-black text-white hover:bg-zinc-800'}`}
                            >
                                💾 Save to Profile
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default SkillsGapAnalyzer;